### ISSUE TITLE
zoxide is never in the PATH

### ISSUE THREAD

**Issue by brandonzylstra** [xxh/xxh-plugin-prerun-zoxide#1]
After installing the zoxide plugin, it is not available:

```
➜  xxh apps-qa-u +s zsh +I xxh-plugin-prerun-zoxide
apps-qa-u:/home/ubuntu/.xxh/.xxh/shells/xxh-shell-zsh not found. Install xxh-shell-zsh? [Y/n]
Install xxh-shell-zsh to apps-qa-u:/home/ubuntu/.xxh
First time upload using rsync (this will be omitted on the next connections)
First run xxh-shell-zsh on apps-qa-u
/home/ubuntu/.xxh/.xxh/shells/xxh-shell-zsh/build/zsh-bin/bin/../../../../../plugins/xxh-plugin-prerun-zoxide/build/pluginrc.zsh:1: command not found: zoxide
ip-10-0-0-230%
```

I'm logging into an Ubuntu server from macOS 11.4.
apps-qa-u is configured in my `~/.ssh/config`.

**Comment by brandonzylstra** [comment]
Okay, this may have more useful clues.  It appears that `mv` is failing for some reason.  Perhaps the `.tar.gz` file is not getting unzipped.

```
➜  xxh +I xxh-plugin-prerun-zoxide
Install xxh-plugin-prerun-zoxide to local /Users/brandon/.xxh/.xxh/plugins/xxh-plugin-prerun-zoxide
Git clone https://github.com/xxh/xxh-plugin-prerun-zoxide
Build xxh-plugin-prerun-zoxide
Check curl
Check grep
Check cut
Check xargs
Check chmod
Downloading zoxide...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   654  100   654    0     0   2151      0 --:--:-- --:--:-- --:--:--  2158
100  987k  100  987k    0     0  1905k      0 --:--:-- --:--:-- --:--:-- 1905k
curl: Saved to filename 'zoxide-v0.7.7-x86_64-unknown-linux-musl.tar.gz'
mv: rename zoxide-x86_64-unknown-linux-musl to zoxide: No such file or directory
chmod: zoxide: No such file or directory
Installed /Users/brandon/.xxh/.xxh/plugins/xxh-plugin-prerun-zoxide
```

**Comment by brandonzylstra** [comment]
Manually extracting it doesn't help because running again gives me a complaint about it already being installed:

```
➜  xxh +I xxh-plugin-prerun-zoxide
Package exists, skip install: /Users/brandon/.xxh/.xxh/plugins/xxh-plugin-prerun-zoxide
```

**Comment by brandonzylstra** [comment]
I found the build.sh file.  It appeared as though I could just run the missing command

```
tar xzvf zoxide-v0.7.7-x86_64-unknown-linux-musl.tar.gz
``` 
and then follow the failed steps.  But that didn't solve the problem. 

The executable is at 

```
/Users/brandon/.xxh/.xxh/plugins/xxh-plugin-prerun-zoxide/build/zoxide/zoxide
```

but that may not be the right place.  I think there may be other things missing from the `build.sh` script.

**Comment by Cobular** [comment]
yeah I'm getting the same issue :( I installed zoxide with cargo, maybe that puts something in the wrong place?

**Comment by Cobular** [comment]
It looks like the place this was taken from (https://github.com/ajeetdsouza/zoxide/blob/06062e92ca591a3758f2d69c9b1cd772a6a378b0/install.sh#L68) is no longer the way it works anymore, as this file has been removed some point before then and now. I think we need to find another way to get zoxide!

EDIT: It seems that in the past they used to distribute binaries directly:
![image](https://user-images.githubusercontent.com/22972550/140271767-becd6ff5-d055-4f18-aa9f-ffa359d8c718.png)
but since then, they've changed to releasing tarballs. These tarballs seem to just have the binary inside, among other things. I'll see if I can get this fixed.
